credentials:
  usernames:
    Catarina:
      email: catarina-pg@hotmail.com
      name: Catarina Gomes
      password: $2b$12$cq3ze6A9Wm6HzSDRTdQpL.lS/aHaCD4VADhspWWw4j2UTlS8nSnY.
      
    guest:
        name:guest
        password:$2b$12$gmPIEP6u8EJTvtz9YYJioOCDOEXZGsGWhJ24dyb3BLTRA9LAmmh2W
        
   
      
cookie:
  expiry_days: 0
  key: Nm8dyaHkHsR6fdizMQizmtQ3noLFhdcU #aus randomkeygen.com
  name: streamlitcookie
  